### ISSUE TITLE
Component Nefit not working anymore in 0.89

### ISSUE THREAD

**Issue by ghost** [marconfus/ha-nefit-ng#8]
Hi marconfus,

Recently saw this in the logging:

`Integrations need to be in their own folder. Change climate/nefit.py to nefit/climate.py. This will stop working soon. February 24, 2019, 1:32 PM loader.py (WARNING) - message first occured at February 24, 2019, 12:08 PM and shows up 3 times`

Just to let you know in case you haven't seen it before.

**Comment by HA-TB303** [comment]
As a result of that the component no longer works in 0.89, even though it did work in 0.88 when renaming it to the new naming convention /custom_components/nefit/climate.py.

It now really needs some love and tender. ;)

**Comment by ghost** [comment]
Indeed, component not working anymore in 0.89 :( So I changed the subject accordingly.

Tried to get Nefit working again by changing config according docs HASS 0.89 "Loading your components":

1. In the config path I changed "custom_components/climate/nefit.py" into "custom_components/nefit/climate.py"

2. Changed configuration.yaml:

```
nefit:
  platform: climate
  name: Heating
  serial: !secret nefit_easy_serial
  accesskey: !secret nefit_easy_accesskey
  password: !secret nefit_easy_password
```

3.  Added an empty file &#95;&#95;init&#95;&#95;.py in the nefit directory (else you'll get error "Unable to find component nefit". According this post the file is required --> https://developers.home-assistant.io/blog/2019/02/19/the-great-migration.html) 



Still not working, get next error:

```
Error during setup of component nefit

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/setup.py", line 154, in _async_setup_component
    component.setup, hass, processed_config)  # type: ignore
AttributeError: module 'custom_components.nefit' has no attribute 'setup'


```

**Comment by marconfus** [comment]
You don‘t have to touch the configuration.yaml. Just rename the folder and file.
I have updated the instructions and fixed the problem with HA 0.89.

**Comment by HA-TB303** [comment]
Thank you for your quick fix. It works again:)

**Comment by marconfus** [comment]
Yes, there are two unrelated things in this ticket. First the renaming of the filestructure and then a breaking change in 0.89

**Comment by ghost** [comment]
It works, thanks :)
